{"uuid":"5418d40a-b311-49ca-b89d-d1d2f85d18a9","historyId":"d49602d1a072c1680db7d9dc015b1b95","fullName":"phptravels.tests.SignupTests.testingInvalidUserSignUp_emailAlreadyExists","labels":[{"name":"package","value":"phptravels.tests.SignupTests"},{"name":"testClass","value":"phptravels.tests.SignupTests"},{"name":"testMethod","value":"testingInvalidUserSignUp_emailAlreadyExists"},{"name":"parentSuite","value":"Surefire suite"},{"name":"suite","value":"Surefire test"},{"name":"subSuite","value":"phptravels.tests.SignupTests"},{"name":"host","value":"santhosh"},{"name":"thread","value":"1355554@santhosh.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Signup"},{"name":"epic","value":"PHPTRAVELS"},{"name":"feature","value":"User Management"},{"name":"severity","value":"critical"}],"links":[{"name":"Test_case","url":"https://en.wikipedia.org/wiki/Test_case","type":"tms"}],"name":"PHPTRAVELS - Invalid User Signup - Email Already Exists","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Method phptravels.tests.SignupTests.testingInvalidUserSignUp_emailAlreadyExists() on instance phptravels.tests.SignupTests@6edaa77a depends on not successfully finished methods \n[phptravels.tests.SignupTests.testingValidUserSignUp() on instance phptravels.tests.SignupTests@6edaa77a]","trace":"java.lang.Throwable: Method phptravels.tests.SignupTests.testingInvalidUserSignUp_emailAlreadyExists() on instance phptravels.tests.SignupTests@6edaa77a depends on not successfully finished methods \n[phptravels.tests.SignupTests.testingValidUserSignUp() on instance phptravels.tests.SignupTests@6edaa77a]\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:806)\n\tat org.testng.TestRunner.run(TestRunner.java:601)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:433)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)\n\tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)\n"},"stage":"finished","description":"Given i already signed up with an email, When I use the same email for new sign up , Then I should get an error message ","steps":[],"attachments":[],"parameters":[],"start":1748067828835,"stop":1748067828835}